[package]
name = "snoop"
version = "0.1.0"
authors = ["kanishkarj <kanishkarj@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
pcap = "0.7.0"